version: '3'
services:
  app:
    image: juanoliveira0101/lab03_docker:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production